[project]
name = "joycaption_comfyui"
description = "Nodes for running the JoyCaption image captioner VLM."
version = "1.0.0"
license = {file = "LICENSE"}
dependencies = ["transformers>=4.51", "torchvision", "torch", "huggingface-hub", "accelerate", "bitsandbytes"]

[project.urls]
Repository = "https://github.com/fpgaminer/joycaption_comfyui"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = ""
DisplayName = "joycaption_comfyui"
Icon = ""
